{
"items" :
    [{ "category": "Traditional", "artist": "Benny Goodman", "label": "Live at Carnegie Hall 1938 [Live]", "year": "1950" },
    { "category": "Traditional", "artist": "Lester Young", "label": "The President Plays with the Oscar Peterson Trio", "year": "1952" },
    { "category": "Traditional", "artist": "Sarah Vaughan / Clifford Brown", "label": "Sarah Vaughan with Clifford Brown", "year": "1954" },
    { "category": "Traditional", "artist": "Dinah Washington", "label": "Dinah Jams [Live]", "year": "1954" },
    { "category": "Traditional", "artist": "Erroll Garner", "label": "Plays Misty", "year": "1954" },
    { "category": "Traditional", "artist": "Louis Armstrong and His All-Stars", "label": "Louis Armstrong Plays W.C. Handy", "year": "1954" },
    { "category": "Traditional", "artist": "Erroll Garner", "label": "Concert by the Sea [Live]", "year": "1955" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "In the Wee Small Hours", "year": "1955" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Songs for Swingin’ Lovers!", "year": "1956" },
    { "category": "Traditional", "artist": "Al Hirt", "label": "Al Hirt’s Jazz Band Ball", "year": "1956" },
    { "category": "Traditional", "artist": "Duke Ellington", "label": "Ellington at Newport [Live]", "year": "1956" },
    { "category": "Traditional", "artist": "Ella Fitzgerald", "label": "Sings the Rodgers and Hart Song Book", "year": "1956" },
    { "category": "Traditional", "artist": "Count Basie / Joe Williams", "label": "Count Basie Swings, Joe Williams Sings", "year": "1956" },
    { "category": "Traditional", "artist": "Lester Young", "label": "The Jazz Giants ’56", "year": "1956" },
    { "category": "Traditional", "artist": "The Lester Young and Teddy Wilson Quartet", "label": "Pres and Teddy", "year": "1956" },
    { "category": "Traditional", "artist": "Oscar Peterson", "label": "Oscar Peterson at the Stratford Shakespearean Festival [Live]", "year": "1956" },
    { "category": "Traditional", "artist": "Quincy Jones", "label": "This Is How I Feel About Jazz", "year": "1957" },
    { "category": "Traditional", "artist": "Count Basie", "label": "Count Basie at Newport [Live]", "year": "1957" },
    { "category": "Traditional", "artist": "Oscar Peterson", "label": "Oscar Peterson at the Concertgebouw [Live]", "year": "1957" },
    { "category": "Traditional", "artist": "Ben Webster", "label": "Soulville", "year": "1957" },
    { "category": "Traditional", "artist": "Bud Freeman", "label": "Chicago/Austin High School Jazz in Hi-Fi", "year": "1957" },
    { "category": "Traditional", "artist": "Count Basie", "label": "April in Paris", "year": "1957" },
    { "category": "Traditional", "artist": "Count Basie", "label": "The Atomic Mr. Basie", "year": "1957" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "A Swingin’ Affair", "year": "1957" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Where Are You?", "year": "1957" },
    { "category": "Traditional", "artist": "Lambert, Hendricks & Ross", "label": "Sing a Song of Basie", "year": "1957" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Come Fly with Me", "year": "1958" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Only the Lonely", "year": "1958" },
    { "category": "Traditional", "artist": "Oscar Peterson", "label": "On the Town with the Oscar Peterson Trio [Live]", "year": "1958" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Come Dance with Me!", "year": "1959" },
    { "category": "Traditional", "artist": "Count Basie / Tony Bennett", "label": "Basie Swings, Bennett Sings", "year": "1959" },
    { "category": "Traditional", "artist": "Dinah Washington", "label": "What a Diff’rence a Day Makes!", "year": "1959" },
    { "category": "Traditional", "artist": "Nina Simone", "label": "Nina Simone at Town Hall [Live]", "year": "1959" },
    { "category": "Traditional", "artist": "Quincy Jones", "label": "The Birth of a Band!", "year": "1959" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "Nice ‘n’ Easy", "year": "1960" },
    { "category": "Traditional", "artist": "Joseph Lamb", "label": "A Study in Classic Ragtime", "year": "1960" },
    { "category": "Traditional", "artist": "George Russell Sextet", "label": "Ezz-Thetics", "year": "1961" },
    { "category": "Traditional", "artist": "Tony Bennett", "label": "I Left My Heart in San Francisco", "year": "1962" },
    { "category": "Traditional", "artist": "Barbra Streisand", "label": "The Barbra Streisand Album", "year": "1963" },
    { "category": "Traditional", "artist": "Duke Ellington / Coleman Hawkins", "label": "Duke Ellington Meets Coleman Hawkins", "year": "1963" },
    { "category": "Traditional", "artist": "Duke Ellington / John Coltrane", "label": "Duke Ellington & John Coltrane", "year": "1963" },
    { "category": "Traditional", "artist": "Oscar Peterson", "label": "Oscar Peterson Trio + One", "year": "1964" },
    { "category": "Traditional", "artist": "Ben Webster", "label": "See You at the Fair", "year": "1964" },
    { "category": "Traditional", "artist": "Frank Sinatra", "label": "September of My Years", "year": "1965" },
    { "category": "Traditional", "artist": "Duke Ellington", "label": "Concert of Sacred Music [Live]", "year": "1966" },
    { "category": "Traditional", "artist": "Joe Williams", "label": "Presenting Joe Williams and Thad Jones / Mel Lewis, The Jazz Orchestra", "year": "1966" },
    { "category": "Traditional", "artist": "Duke Ellington", "label": "…And His Mother Called Him Bill", "year": "1967" },
    { "category": "Traditional", "artist": "Nina Simone", "label": "High Priestess of Soul", "year": "1967" },
    { "category": "Traditional", "artist": "Nina Simone", "label": "Nina Simone Sings the Blues", "year": "1967" },
    { "category": "Traditional", "artist": "Tony Bennett", "label": "Snowfall: The Tony Bennett Christmas Album", "year": "1968" },
    { "category": "Traditional", "artist": "Art Tatum", "label": "Piano Starts Here [Compilation]", "year": "1968" },
    { "category": "Traditional", "artist": "Oscar Peterson", "label": "My Favorite Instrument", "year": "1968" },
    { "category": "Traditional", "artist": "Quincy Jones", "label": "Walking in Space", "year": "1969" },
    { "category": "Traditional", "artist": "World’s Greatest Jazz Band", "label": "Live [Live]", "year": "1970" },
    { "category": "Traditional", "artist": "Teddy Wilson", "label": "With Billie in Mind", "year": "1972" },
    { "category": "Traditional", "artist": "Oscar Peterson / Joe Pass / Niels-Henning Ørsted Pedersen", "label": "The Trio [Live]", "year": "1973" },
    { "category": "Traditional", "artist": "Gunther Schuller", "label": "Art of Scott Joplin", "year": "1974" },
    { "category": "Traditional", "artist": "Preservation Hall Jazz Band", "label": "New Orleans, Vol. 1", "year": "1977" },
    { "category": "Traditional", "artist": "Dick Hyman", "label": "The Music of Jelly Roll Morton", "year": "1978" },
    { "category": "Traditional", "artist": "James Booker", "label": "Classified", "year": "1982" },
    { "category": "Traditional", "artist": "Bobby McFerrin", "label": "The Voice", "year": "1984" },
    { "category": "Traditional", "artist": "Barbra Streisand", "label": "The Broadway Album", "year": "1985" },
    { "category": "Traditional", "artist": "Ron Carter", "label": "Telephone [Live]", "year": "1985" },
    { "category": "Traditional", "artist": "Jelly Roll Morton", "label": "The Pearls [Compilation]", "year": "1988" },
    { "category": "Traditional", "artist": "Duke Ellington", "label": "The OKeh Ellington [Compilation]", "year": "1991" },
    { "category": "Traditional", "artist": "Joe Henderson", "label": "Lush Life: The Music of Billy Strayhorn", "year": "1992" },
    { "category": "Traditional", "artist": "Cassandra Wilson", "label": "Blue Light ‘til Dawn", "year": "1993" },
    { "category": "Traditional", "artist": "Original Cast Recording", "label": "Songs from Ragtime [Soundtrack]", "year": "1996" },
    { "category": "Traditional", "artist": "Nina Simone", "label": "Anthology [Compilation]", "year": "2003" },
    { "category": "Fusion", "artist": "Miles Davis", "label": "In A Silent Way", "year": "1969" },
    { "category": "Fusion", "artist": "Miles Davis", "label": "Bitches Brew", "year": "1969" },
    { "category": "Fusion", "artist": "Mahavishnu Orchestra ", "label": "The Inner Mounting Flame", "year": "1971" },
    { "category": "Fusion", "artist": "Weather Report", "label": "Weather Report", "year": "1971" },
    { "category": "Fusion", "artist": "Soft Machine", "label": "Third", "year": "1970" },
    { "category": "Fusion", "artist": "Chick Corea", "label": "Return To Forever", "year": "1972" },
    { "category": "Fusion", "artist": "Tribal Tech", "label": "Tribal Tech", "year": "1991" },
    { "category": "Fusion", "artist": "Allan Holdsworth", "label": "Atavachron", "year": "1986" },
    { "category": "Fusion", "artist": "Tony Williams Lifetime", "label": "Emergency!", "year": "1969" },
    { "category": "Fusion", "artist": "Don Ellis Orchestra", "label": "Electric Bath", "year": "1967" },
    { "category": "Fusion", "artist": "Weather Report ", "label": "8:30", "year": "1979" },
    { "category": "Fusion", "artist": "Carlos Santana & John McLaughlin", "label": "Love, Devotion & Surrender", "year": "1972" },
    { "category": "Fusion", "artist": "Tribal Tech", "label": "Rocket Science", "year": "2000" },
    { "category": "Fusion", "artist": "Santana", "label": "Lotus", "year": "1974" },
    { "category": "Fusion", "artist": "Blood, Sweat & Tears", "label": "Blood, Sweat & Tears", "year": "1969" },
    { "category": "Fusion", "artist": "Mahavishnu Orchestra", "label": "The Lost Trident Sessions", "year": "1999" },
    { "category": "Fusion", "artist": "Chicago", "label": "Chicago Transit Authority", "year": "1969" },
    { "category": "Fusion", "artist": "Return To Forever", "label": "Light As A Feather", "year": "1972" },
    { "category": "Fusion", "artist": "Mahavishnu Orchestra", "label": "Birds Of Fire", "year": "1972" },
    { "category": "Fusion", "artist": "Planet X", "label": "Quantum", "year": "2007" },
    { "category": "Fusion", "artist": "Miles Davis", "label": "Amandla", "year": "1989" },
    { "category": "Fusion", "artist": "Herbie Hancock", "label": "Head Hunters", "year": "1973" },
    { "category": "Fusion", "artist": "Frank Zappa", "label": "The Grand Wazoo", "year": "1973" },
    { "category": "Fusion", "artist": "Traffic", "label": "The Low Spark Of High Heeled Boys", "year": "1971" },
    { "category": "Fusion", "artist": "Soft Machine", "label": "Six", "year": "1973" },
    { "category": "Fusion", "artist": "Allan Holdsworth", "label": "Sand", "year": "1987" },
    { "category": "Fusion", "artist": "Tribal Tech", "label": "Reality Check", "year": "1995" },
    { "category": "Fusion", "artist": "Steely Dan", "label": "Aja", "year": "1977" },
    { "category": "Fusion", "artist": "John Scofield", "label": "Pick Hits Live", "year": "1987" },
    { "category": "Fusion", "artist": "Al Di Meola", "label": "Elegant Gypsy", "year": "1977" },
    { "category": "Fusion", "artist": "Michael Brecker", "label": "Michael Brecker", "year": "1986" },
    { "category": "Fusion", "artist": "Billy Cobham", "label": "Spectrum", "year": "1973" },
    { "category": "Fusion", "artist": "Frank Zappa", "label": "Shut Up 'N Play Yer Guitar", "year": "1981" },
    { "category": "Fusion", "artist": "The New Tony Williams Lifetime", "label": "Believe It", "year": "1975" },
    { "category": "Fusion", "artist": "Larry Coryell", "label": "Live At The Village Gate", "year": "1971" },
    { "category": "Fusion", "artist": "Andy Summers", "label": "World Gone Strange", "year": "1991" },
    { "category": "Fusion", "artist": "Bob Berg", "label": "Short Stories", "year": "1987" },
    { "category": "Fusion", "artist": "Return To Forever", "label": "Where Have I Known You Before", "year": "1974" },
    { "category": "Fusion", "artist": "Eddie Henderson", "label": "Sunburst", "year": "1975" },
    { "category": "Fusion", "artist": "Steps Ahead", "label": "Steps Ahead", "year": "1983" },
    { "category": "Fusion", "artist": "Christian McBride", "label": "Vertical Vision", "year": "2003" },
    { "category": "Fusion", "artist": "Soft Machine", "label": "Seven", "year": "1974" },
    { "category": "Fusion", "artist": "Leni Stern", "label": "Closer To The Light", "year": "1989" },
    { "category": "Fusion", "artist": "Return To Forever", "label": "Romantic Warrior", "year": "1976" },
    { "category": "Fusion", "artist": "Tom Coster", "label": "The Forbidden Zone", "year": "1994" },
    { "category": "Fusion", "artist": "Weather Report", "label": "I Sing The Body Electric", "year": "1972" },
    { "category": "Fusion", "artist": "Pat Metheny", "label": "Pat Metheny Group", "year": "1978" },
    { "category": "Fusion", "artist": "Stanley Clarke", "label": "School Days", "year": "1976" },
    { "category": "Fusion", "artist": "Bill Evans", "label": "Petite Blonde", "year": "1992" },
    { "category": "Fusion", "artist": "Dennis Chambers", "label": "Getting Even", "year": "1998" },
    { "category": "Fusion", "artist": "Brand X", "label": "Unorthodox Behaviour", "year": "1976" },
    { "category": "Fusion", "artist": "Herbie Hancock", "label": "Crossings", "year": "1972" },
    { "category": "Fusion", "artist": "Jean-Luc Ponty", "label": "King Kong", "year": "1969" },
    { "category": "Fusion", "artist": "Vital Tech Tones", "label": "Vital Tech Tones", "year": "1998" },
    { "category": "Fusion", "artist": "Scott Kinsey", "label": "Kinesethetics", "year": "2006" },
    { "category": "Fusion", "artist": "Flora Purim", "label": "Stories To Tell", "year": "1974" },
    { "category": "Fusion", "artist": "Lonnie Liston Smith & The Cosmic Echoes", "label": "Expansions", "year": "1974" },
    { "category": "Fusion", "artist": "Bob Berg", "label": "Cycles", "year": "1998" },
    { "category": "Fusion", "artist": "Metro", "label": "Metro", "year": "1994" },
    { "category": "Fusion", "artist": "Miles Davis", "label": "Tutu", "year": "1986" },
    { "category": "Fusion", "artist": "Hatfield & The North", "label": "The Rotters' Club", "year": "1975" },
    { "category": "Fusion", "artist": "Marc Johnson", "label": "Bass Desires", "year": "1985" },
    { "category": "Fusion", "artist": "National Health", "label": "National Health", "year": "1977" },
    { "category": "Fusion", "artist": "Nucleus", "label": "We'll Talk About It Later", "year": "1971" },
    { "category": "Fusion", "artist": "Mitchel Forman", "label": "Train Of Thought", "year": "1985" },
    { "category": "Fusion", "artist": "Mike Stern", "label": "Upside Downside", "year": "1986" },
    { "category": "Fusion", "artist": "Mark-Almond", "label": "To The Heart", "year": "1976" },
    { "category": "Fusion", "artist": "Stan Getz", "label": "Captain Marvel", "year": "1972" },
    { "category": "Fusion", "artist": "Blood, Sweat & Tears", "label": "B,S & T 4", "year": "1971" },
    { "category": "Fusion", "artist": "Dreams", "label": "Dreams", "year": "1969" },
    { "category": "Fusion", "artist": "Larry Coryell", "label": "Introducing The Eleventh House", "year": "1974" },
    { "category": "Fusion", "artist": "Chad Wackerman", "label": "Forty Reasons", "year": "1991" },
    { "category": "Fusion", "artist": "Wayne Johnson", "label": "Arrowhead", "year": "1980" },
    { "category": "Fusion", "artist": "John Scofield", "label": "Still Warm", "year": "1986" },
    { "category": "Fusion", "artist": "Allan Holdsworth", "label": "Secrets", "year": "1989" },
    { "category": "Fusion", "artist": "Don Ellis Orchestra", "label": "Don Ellis At Fillmore", "year": "1970" },
    { "category": "Fusion", "artist": "Billy Cobham", "label": "Crosswinds", "year": "1974" },
    { "category": "Fusion", "artist": "Gong", "label": "Expresso II", "year": "1978" },
    { "category": "Fusion", "artist": "Chroma", "label": "Music On The Edge", "year": "1991" },
    { "category": "Fusion", "artist": "Passport", "label": "Cross-Collateral", "year": "1975" },
    { "category": "Fusion", "artist": "Compost", "label": "Compost", "year": "1971" },
    { "category": "Fusion", "artist": "If", "label": "If 2", "year": "1970" },
    { "category": "Fusion", "artist": "Johnny McLaughlin", "label": "Electric Guitarist", "year": "1978" },
    { "category": "Fusion", "artist": "John Scofield", "label": "Blue Matter", "year": "1986" },
    { "category": "Fusion", "artist": "Jean Luc-Ponty", "label": "Enigmatic Ocean", "year": "1977" },
    { "category": "Fusion", "artist": "Tribal Tech", "label": "Thick", "year": "1999" },
    { "category": "Fusion", "artist": "Bill Frisell & Vernon Reid", "label": "Smash & Scatteration", "year": "1984" },
    { "category": "Fusion", "artist": "Mirolslav Vitous", "label": "Mountain In The Clouds", "year": "1969" },
    { "category": "Fusion", "artist": "CAB", "label": "CAB 2", "year": "2001" },
    { "category": "Fusion", "artist": "John McLaughlin", "label": "My Goals Beyond", "year": "1970" },
    { "category": "Fusion", "artist": "Soft Machine", "label": "Volume Two", "year": "1969" },
    { "category": "Fusion", "artist": "Planet X", "label": "MoonBabies", "year": "2002" },
    { "category": "Fusion", "artist": "Isotope", "label": "Illusion", "year": "1975" },
    { "category": "Fusion", "artist": "Jan Hammer & Jerry Goodman", "label": "Like Children", "year": "1975" },
    { "category": "Fusion", "artist": "Catalyst", "label": "Unity", "year": "1974" },
    { "category": "Fusion", "artist": "Michael Landau Group", "label": "Live", "year": "2006" },
    { "category": "Fusion", "artist": "Allan Holdsworth", "label": "Wardenclyffe Tower", "year": "1992" },
    { "category": "Fusion", "artist": "Vinnie Colaiuta", "label": "Vinnie Colaiuta", "year": "1994" },
    { "category": "Fusion", "artist": "Marcus Miller", "label": "Live And More", "year": "1998" },
    { "category": "Fusion", "artist": "Kazumi Watanabe", "label": "Mobo II", "year": "1984" },
    { "category": "Avant-garde", "artist": "Ornette Coleman", "label": "The Shape of Jazz to Come", "year": "1959" },
    { "category": "Avant-garde", "artist": "Ornette Coleman", "label": "Change of the Century", "year": "1960" },
    { "category": "Avant-garde", "artist": "Eric Dolphy", "label": "Out There", "year": "1960" },
    { "category": "Avant-garde", "artist": "John Coltrane", "label": "My Favorite Things", "year": "1961" },
    { "category": "Avant-garde", "artist": "Ornette Coleman", "label": "Free Jazz: A Collective Improvisation", "year": "1961" },
    { "category": "Avant-garde", "artist": "Steve Lacy", "label": "The Straight Horn of Steve Lacy", "year": "1961" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "Oh Yeah", "year": "1962" },
    { "category": "Avant-garde", "artist": "Jackie McLean", "label": "Let Freedom Ring", "year": "1962" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "The Black Saint and the Sinner Lady", "year": "1963" },
    { "category": "Avant-garde", "artist": "Eric Dolphy", "label": "Iron Man", "year": "1963" },
    { "category": "Avant-garde", "artist": "John Coltrane", "label": "Live at Birdland [Live]", "year": "1963" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "Mingus Mingus Mingus Mingus Mingus", "year": "1964" },
    { "category": "Avant-garde", "artist": "Andrew Hill", "label": "Point of Departure", "year": "1964" },
    { "category": "Avant-garde", "artist": "Archie Shepp", "label": "Four for Trane", "year": "1964" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "The Great Concert of Charles Mingus [Live]", "year": "1964" },
    { "category": "Avant-garde", "artist": "Eric Dolphy", "label": "Out to Lunch!", "year": "1964" },
    { "category": "Avant-garde", "artist": "Jackie McLean", "label": "Destination… Out!", "year": "1964" },
    { "category": "Avant-garde", "artist": "John Coltrane", "label": "A Love Supreme", "year": "1965" },
    { "category": "Avant-garde", "artist": "Rahsaan Roland Kirk", "label": "Rip, Rig and Panic", "year": "1965" },
    { "category": "Avant-garde", "artist": "Albert Ayler", "label": "Spiritual Unity", "year": "1965" },
    { "category": "Avant-garde", "artist": "Archie Shepp", "label": "Fire Music", "year": "1965" },
    { "category": "Avant-garde", "artist": "John Coltrane", "label": "Ascension", "year": "1966" },
    { "category": "Avant-garde", "artist": "Cecil Taylor", "label": "Unit Structures", "year": "1966" },
    { "category": "Avant-garde", "artist": "Sonny Rollins", "label": "East Broadway Run Down", "year": "1966" },
    { "category": "Avant-garde", "artist": "Jackie McLean", "label": "New and Old Gospel", "year": "1967" },
    { "category": "Avant-garde", "artist": "Don Cherry", "label": "Eternal Rhythm [Live]", "year": "1969" },
    { "category": "Avant-garde", "artist": "George Russell", "label": "Electronic Sonata for Souls Loved by Nature", "year": "1969" },
    { "category": "Avant-garde", "artist": "Pharaoh Sanders", "label": "Karma", "year": "1969" },
    { "category": "Avant-garde", "artist": "Sun Ra", "label": "Atlantis", "year": "1969" },
    { "category": "Avant-garde", "artist": "Barre Phillips / Dave Holland", "label": "Music from Two Basses", "year": "1971" },
    { "category": "Avant-garde", "artist": "Joe Farrell", "label": "Outback", "year": "1971" },
    { "category": "Avant-garde", "artist": "Archie Shepp", "label": "The Cry of My People", "year": "1972" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "Let My Children Hear Music", "year": "1972" },
    { "category": "Avant-garde", "artist": "McCoy Tyner", "label": "Sahara", "year": "1972" },
    { "category": "Avant-garde", "artist": "McCoy Tyner", "label": "Echoes of a Friend", "year": "1972" },
    { "category": "Avant-garde", "artist": "Ornette Coleman", "label": "Science Fiction", "year": "1972" },
    { "category": "Avant-garde", "artist": "Keith Jarrett", "label": "Solo Concerts: Bremen/Lausanne [Live]", "year": "1973" },
    { "category": "Avant-garde", "artist": "McCoy Tyner", "label": "Enlightenment [Live]", "year": "1973" },
    { "category": "Avant-garde", "artist": "Rahsaan Roland Kirk", "label": "Bright Moments [Live]", "year": "1973" },
    { "category": "Avant-garde", "artist": "Sun Ra", "label": "Space Is the Place", "year": "1973" },
    { "category": "Avant-garde", "artist": "Cecil Taylor", "label": "Silent Tongues [Live]", "year": "1974" },
    { "category": "Avant-garde", "artist": "Keith Jarrett", "label": "The Köln Concert [Live]", "year": "1975" },
    { "category": "Avant-garde", "artist": "Charles Mingus", "label": "Mingus at Antibes [Live]", "year": "1976" },
    { "category": "Avant-garde", "artist": "Cecil Taylor", "label": "The Great Concert of Cecil Taylor [Live]", "year": "1977" },
    { "category": "Avant-garde", "artist": "Archie Shepp", "label": "Attica Blues Big Band", "year": "1979" },
    { "category": "Avant-garde", "artist": "James Blood Ulmer", "label": "Tales of Captain Black", "year": "1979" },
    { "category": "Avant-garde", "artist": "Max Roach / Anthony Braxton", "label": "One in Two Two in One [Live]", "year": "1979" },
    { "category": "Avant-garde", "artist": "McCoy Tyner", "label": "Horizon", "year": "1979" },
    { "category": "Avant-garde", "artist": "Jack DeJohnette", "label": "Special Edition", "year": "1980" },
    { "category": "Avant-garde", "artist": "Ronald Shannon Jackson", "label": "Eye on You", "year": "1980" },
    { "category": "Avant-garde", "artist": "Derek Bailey / Steve Lacy", "label": "Outcome", "year": "1983" },
    { "category": "Avant-garde", "artist": "James Blood Ulmer", "label": "Odyssey", "year": "1984" },
    { "category": "Avant-garde", "artist": "Charlie Haden", "label": "Quartet West", "year": "1987" },
    { "category": "Avant-garde", "artist": "Marilyn Crispell / Irène Schweizer", "label": "Overlapping Hands: Eight Segments", "year": "1990" },
    { "category": "Avant-garde", "artist": "Evan Parker", "label": "Process and Reality", "year": "1991" },
    { "category": "Avant-garde", "artist": "Steve Lacy", "label": "Itinerary [Live]", "year": "1991" },
    { "category": "Avant-garde", "artist": "Bill Frisell", "label": "Have a Little Faith", "year": "1992" },
    { "category": "Avant-garde", "artist": "Steve Lacy", "label": "Duets: Associates", "year": "1997" },
    { "category": "Latin", "artist": "Kenny Dorham", "label": "Afro-Cuban", "year": "1955" },
    { "category": "Latin", "artist": "Cal Tjader", "label": "Jazz at the Blackhawk [Live]", "year": "1957" },
    { "category": "Latin", "artist": "Dizzy Gillespie", "label": "Dizzy Gillespie at Newport [Live]", "year": "1957" },
    { "category": "Latin", "artist": "Tito Puente", "label": "Dance Mania", "year": "1958" },
    { "category": "Latin", "artist": "Cal Tjader", "label": "Monterey Concerts [Live]", "year": "1959" },
    { "category": "Latin", "artist": "João Gilberto", "label": "Brazil’s Brilliant João Gilberto", "year": "1961" },
    { "category": "Latin", "artist": "Dizzy Gillespie", "label": "An Electrifying Evening with the Dizzy Gillespie Quintet [Live]", "year": "1961" },
    { "category": "Latin", "artist": "Yusef Lateef", "label": "Eastern Sounds", "year": "1961" },
    { "category": "Latin", "artist": "Vince Guaraldi Trio", "label": "Jazz Impressions of Black Orpheus", "year": "1962" },
    { "category": "Latin", "artist": "Charlie Byrd / Stan Getz", "label": "Jazz Samba", "year": "1962" },
    { "category": "Latin", "artist": "Eddie Palmieri", "label": "La Perfecta", "year": "1962" },
    { "category": "Latin", "artist": "Stan Getz / João Gilberto", "label": "Getz/Gilberto", "year": "1964" },
    { "category": "Latin", "artist": "Yusef Lateef", "label": "Live at Pep’s [Live]", "year": "1964" },
    { "category": "Latin", "artist": "Yusef Lateef", "label": "Live at Pep’s, Vol. 2 [Live]", "year": "1964" },
    { "category": "Latin", "artist": "Antonio Carlos Jobim", "label": "Wave", "year": "1967" },
    { "category": "Latin", "artist": "Caetano Veloso", "label": "Caetano Veloso Tropicália", "year": "1968" },
    { "category": "Latin", "artist": "Ray Barretto", "label": "Acid", "year": "1968" },
    { "category": "Latin", "artist": "Milton Nascimento", "label": "Courage", "year": "1969" },
    { "category": "Latin", "artist": "Caetano Veloso", "label": "Caetano Veloso A Little More Blue", "year": "1971" },
    { "category": "Latin", "artist": "Chico Buarque", "label": "Construção", "year": "1971" },
    { "category": "Latin", "artist": "Gato Barbieri", "label": "Last Tango in Paris [Soundtrack]", "year": "1972" },
    { "category": "Latin", "artist": "Luiz Bonfá", "label": "Introspection", "year": "1972" },
    { "category": "Latin", "artist": "Lô Borges / Milton Nascimento", "label": "Clube Da Esquina", "year": "1972" },
    { "category": "Latin", "artist": "Eddie Palmieri", "label": "The Sun of Latin Music", "year": "1974" },
    { "category": "Latin", "artist": "Rubén Blades / Willie Colón", "label": "Siembra", "year": "1978" },
    { "category": "Latin", "artist": "Ástor Piazzolla", "label": "Tango: Zero Hour", "year": "1986" },
    { "category": "Latin", "artist": "Arturo Sandoval", "label": "Straight Ahead", "year": "1988" },
    { "category": "Latin", "artist": "Chico Buarque", "label": "Chico Buarque - Morros Dois Irmanos", "year": "1989" },
    { "category": "Latin", "artist": "Bebo Valdés", "label": "Bebo Rides Again", "year": "1994" },
    { "category": "Latin", "artist": "Buena Vista Social Club", "label": "Buena Vista Social Club", "year": "1997" },
    { "category": "Latin", "artist": "Luiz Bonfá", "label": "Solo in Rio 1959 [Live]", "year": "2005" },
    { "category": "Cool", "artist": "Gerry Mulligan", "label": "Gerry Mulligan Quartet, Vol. 1", "year": "1953" },
    { "category": "Cool", "artist": "Gerry Mulligan", "label": "Gerry Mulligan Quartet, Vol. 2", "year": "1953" },
    { "category": "Cool", "artist": "The Dave Brubeck Quartet", "label": "Jazz Goes to College [Live]", "year": "1954" },
    { "category": "Cool", "artist": "June Christy", "label": "Something Cool", "year": "1954" },
    { "category": "Cool", "artist": "Barney Kessel", "label": "Vol. 3: To Swing or Not to Swing", "year": "1955" },
    { "category": "Cool", "artist": "Shelly Manne", "label": "My Fair Lady", "year": "1956" },
    { "category": "Cool", "artist": "Art Pepper", "label": "Art Pepper Meets the Rhythm Section", "year": "1957" },
    { "category": "Cool", "artist": "Gil Evans", "label": "Gil Evans & Ten", "year": "1957" },
    { "category": "Cool", "artist": "Miles Davis", "label": "‘Round About Midnight", "year": "1957" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Birth of the Cool [Compilation]", "year": "1957" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Miles Ahead", "year": "1957" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Milestones", "year": "1958" },
    { "category": "Cool", "artist": "Annie Ross / Gerry Mulligan Quartet", "label": "Annie Ross Sings a Song with Mulligan!", "year": "1958" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Porgy and Bess", "year": "1958" },
    { "category": "Cool", "artist": "Stan Getz / Gerry Mulligan / Harry “Sweets” Edison / Oscar Peterson", "label": "Jazz Giants ’58", "year": "1958" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Kind of Blue", "year": "1959" },
    { "category": "Cool", "artist": "The Dave Brubeck Quartet", "label": "Time Out", "year": "1959" },
    { "category": "Cool", "artist": "Gerry Mulligan", "label": "What Is There to Say?", "year": "1959" },
    { "category": "Cool", "artist": "Gerry Mulligan / Ben Webster", "label": "Gerry Mulligan Meets Ben Webster", "year": "1959" },
    { "category": "Cool", "artist": "Art Pepper", "label": "Art Pepper + Eleven Modern Jazz Classics", "year": "1959" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Sketches of Spain", "year": "1960" },
    { "category": "Cool", "artist": "Gerry Mulligan", "label": "Gerry Mulligan and the Concert Band at the Village Vanguard [Live]", "year": "1960" },
    { "category": "Cool", "artist": "The Modern Jazz Quartet", "label": "European Concert [Live]", "year": "1960" },
    { "category": "Cool", "artist": "Bill Evans Trio", "label": "Sunday at the Village Vanguard [Live]", "year": "1961" },
    { "category": "Cool", "artist": "Bill Evans Trio", "label": "Waltz for Debby", "year": "1961" },
    { "category": "Cool", "artist": "The Modern Jazz Quartet", "label": "Lonely Woman", "year": "1962" },
    { "category": "Cool", "artist": "Andrew Hill", "label": "Black Fire", "year": "1964" },
    { "category": "Cool", "artist": "Vince Guaraldi", "label": "Jazz Impressions of a Boy Named Charlie Brown", "year": "1964" },
    { "category": "Cool", "artist": "Vince Guaraldi Trio", "label": "A Charlie Brown Christmas [Soundtrack]", "year": "1965" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Miles Smiles", "year": "1967" },
    { "category": "Cool", "artist": "Stan Getz", "label": "Sweet Rain", "year": "1967" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Nefertiti", "year": "1968" },
    { "category": "Cool", "artist": "Lee Konitz", "label": "The Lee Konitz Duets", "year": "1968" },
    { "category": "Cool", "artist": "Miles Davis", "label": "In a Silent Way", "year": "1969" },
    { "category": "Cool", "artist": "George Benson", "label": "Shape of Things to Come", "year": "1969" },
    { "category": "Cool", "artist": "The Tony Williams Lifetime", "label": "Emergency!", "year": "1969" },
    { "category": "Cool", "artist": "Miles Davis", "label": "Bitches Brew", "year": "1970" },
    { "category": "Cool", "artist": "John McLaughlin", "label": "My Goal’s Beyond", "year": "1970" },
    { "category": "Cool", "artist": "Freddie Hubbard", "label": "Red Clay", "year": "1970" },
    { "category": "Cool", "artist": "Freddie Hubbard", "label": "Straight Life", "year": "1971" },
    { "category": "Cool", "artist": "Miles Davis", "label": "A Tribute to Jack Johnson", "year": "1971" },
    { "category": "Cool", "artist": "Weather Report", "label": "Weather Report", "year": "1971" },
    { "category": "Cool", "artist": "Mahavishnu Orchestra", "label": "The Inner Mounting Flame", "year": "1971" },
    { "category": "Cool", "artist": "George Benson", "label": "Beyond the Blue Horizon", "year": "1971" },
    { "category": "Cool", "artist": "Herbie Hancock", "label": "Mwandishi", "year": "1971" },
    { "category": "Cool", "artist": "Miles Davis", "label": "On the Corner", "year": "1972" },
    { "category": "Cool", "artist": "Chick Corea / Return to Forever", "label": "Return to Forever", "year": "1972" },
    { "category": "Cool", "artist": "Chick Corea / Return to Forever", "label": "Light as a Feather", "year": "1972" },
    { "category": "Cool", "artist": "Donald Byrd", "label": "Black Byrd", "year": "1972" },
    { "category": "Cool", "artist": "Herbie Hancock", "label": "Crossings", "year": "1972" },
    { "category": "Cool", "artist": "Mahavishnu Orchestra", "label": "Birds of Fire", "year": "1973" },
    { "category": "Cool", "artist": "Herbie Hancock", "label": "Head Hunters", "year": "1973" },
    { "category": "Cool", "artist": "Lonnie Liston Smith and the Cosmic Echoes", "label": "Expansions", "year": "1974" },
    { "category": "Cool", "artist": "Zoot Sims", "label": "Zoot Sims and the Gershwin Brothers", "year": "1975" },
    { "category": "Cool", "artist": "Jaco Pastorious", "label": "Jaco Pastorious", "year": "1976" },
    { "category": "Cool", "artist": "Weather Report", "label": "Heavy Weather", "year": "1977" },
    { "category": "Cool", "artist": "Al Di Meola", "label": "Elegant Gypsy", "year": "1977" },
    { "category": "Cool", "artist": "Lee Konitz", "label": "The Lee Konitz Nonet", "year": "1977" },
    { "category": "Cool", "artist": "Al Di Meola", "label": "Casino", "year": "1978" },
    { "category": "Cool", "artist": "Art Pepper", "label": "Straight Life", "year": "1979" },
    { "category": "Cool", "artist": "Al Di Meola", "label": "Splendido Hotel", "year": "1980" },
    { "category": "Cool", "artist": "Michael Brecker", "label": "Michael Brecker", "year": "1987" },
    { "category": "Cool", "artist": "The Modern Jazz Quartet", "label": "The Complete Last Concert [Live]", "year": "1988" },
    { "category": "Cool", "artist": "Tony Williams", "label": "Tokyo Live [Live]", "year": "1992" },
    { "category": "Bebop", "artist": "Lennie Tristano", "label": "Crosscurrents", "year": "1949" },
    { "category": "Bebop", "artist": "Lee Konitz", "label": "Subconscious-Lee", "year": "1950" },
    { "category": "Bebop", "artist": "Bud Powell", "label": "The Amazing Bud Powell", "year": "1951" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "Genius of Modern Music: Volume 1 [Compilation]", "year": "1951" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "Genius of Modern Music: Volume 2 [Compilation]", "year": "1952" },
    { "category": "Bebop", "artist": "The Quintet", "label": "Jazz at Massey Hall [Live]", "year": "1953" },
    { "category": "Bebop", "artist": "Roy Eldridge / Dizzy Gillespie", "label": "Roy and Diz", "year": "1954" },
    { "category": "Bebop", "artist": "Horace Silver", "label": "Horace Silver and the Jazz Messengers", "year": "1955" },
    { "category": "Bebop", "artist": "Sonny Rollins", "label": "Saxophone Colossus", "year": "1956" },
    { "category": "Bebop", "artist": "Bud Powell", "label": "The Genius of Bud Powell", "year": "1956" },
    { "category": "Bebop", "artist": "Charles Mingus", "label": "Pithecanthropus Erectus", "year": "1956" },
    { "category": "Bebop", "artist": "Sonny Rollins", "label": "Sonny Rollins Plus 4", "year": "1956" },
    { "category": "Bebop", "artist": "Charles Mingus", "label": "The Clown", "year": "1957" },
    { "category": "Bebop", "artist": "Hampton Hawes", "label": "Four!", "year": "1957" },
    { "category": "Bebop", "artist": "John Coltrane", "label": "Blue Train", "year": "1957" },
    { "category": "Bebop", "artist": "Johnny Griffin", "label": "A Blowin’ Session", "year": "1957" },
    { "category": "Bebop", "artist": "Miles Davis", "label": "Bags’ Groove", "year": "1957" },
    { "category": "Bebop", "artist": "Sonny Rollins", "label": "A Night at the Village Vanguard", "year": "1957" },
    { "category": "Bebop", "artist": "Sonny Rollins", "label": "Way Out West", "year": "1957" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "Brilliant Corners", "year": "1957" },
    { "category": "Bebop", "artist": "Cannonball Adderley", "label": "Somethin’ Else", "year": "1958" },
    { "category": "Bebop", "artist": "Miles Davis", "label": "Relaxin’ with the Miles Davis Quintet", "year": "1958" },
    { "category": "Bebop", "artist": "Art Blakey and the Jazz Messengers", "label": "Moanin’", "year": "1959" },
    { "category": "Bebop", "artist": "Miles Davis", "label": "Workin’ with the Miles Davis Quintet", "year": "1959" },
    { "category": "Bebop", "artist": "Charles Mingus", "label": "Mingus Ah Um", "year": "1959" },
    { "category": "Bebop", "artist": "Horace Silver", "label": "Finger Poppin’ with the Horace Silver Quintet", "year": "1959" },
    { "category": "Bebop", "artist": "Miles Davis", "label": "Miles Davis and the Modern Jazz Giants", "year": "1959" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "The Thelonious Monk Orchestra at Town Hall [Live]", "year": "1959" },
    { "category": "Bebop", "artist": "Tommy Flanagan / John Coltrane / Kenny Burrell / Idrees Sulieman", "label": "The Cats", "year": "1959" },
    { "category": "Bebop", "artist": "John Coltrane", "label": "Giant Steps", "year": "1960" },
    { "category": "Bebop", "artist": "Charles Mingus", "label": "Blues and Roots", "year": "1960" },
    { "category": "Bebop", "artist": "Eric Dolphy", "label": "Eric Dolphy", "year": "1960" },
    { "category": "Bebop", "artist": "Hank Mobley", "label": "Soul Station", "year": "1960" },
    { "category": "Bebop", "artist": "Max Roach", "label": "We Insist! Max Roach’s Freedom Now Suite", "year": "1960" },
    { "category": "Bebop", "artist": "Wes Montgomery", "label": "The Incredible Jazz Guitar of Wes Montgomery", "year": "1960" },
    { "category": "Bebop", "artist": "The Young Lions", "label": "The Young Lions", "year": "1960" },
    { "category": "Bebop", "artist": "Miles Davis", "label": "Steamin’ with the Miles Davis Quintet", "year": "1961" },
    { "category": "Bebop", "artist": "Oliver Nelson", "label": "The Blues and the Abstract Truth", "year": "1961" },
    { "category": "Bebop", "artist": "Milt Jackson / John Coltrane", "label": "Bags & Trane", "year": "1961" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "Thelonious Monk with John Coltrane", "year": "1961" },
    { "category": "Bebop", "artist": "Eddie Harris", "label": "Exodus to Jazz", "year": "1961" },
    { "category": "Bebop", "artist": "Freddie Hubbard", "label": "Ready for Freddie", "year": "1961" },
    { "category": "Bebop", "artist": "Gene Ammons / Sonny Stitt", "label": "Boss Tenors", "year": "1961" },
    { "category": "Bebop", "artist": "Jimmy Smith", "label": "Midnight Special", "year": "1961" },
    { "category": "Bebop", "artist": "Max Roach", "label": "Percussion Bitter Sweet", "year": "1961" },
    { "category": "Bebop", "artist": "Phil Woods", "label": "Rights of Swing", "year": "1961" },
    { "category": "Bebop", "artist": "Roland Kirk", "label": "Kirk’s Work", "year": "1961" },
    { "category": "Bebop", "artist": "Charles Mingus", "label": "New Tijuana Moods", "year": "1962" },
    { "category": "Bebop", "artist": "Dexter Gordon", "label": "Go", "year": "1962" },
    { "category": "Bebop", "artist": "Ike Quebec", "label": "Blue & Sentimental", "year": "1962" },
    { "category": "Bebop", "artist": "Jimmy Smith", "label": "Bashin’: The Unpredictable Jimmy Smith", "year": "1962" },
    { "category": "Bebop", "artist": "Walt Dickerson", "label": "To My Queen", "year": "1962" },
    { "category": "Bebop", "artist": "Wes Montgomery", "label": "Full House [Live]", "year": "1962" },
    { "category": "Bebop", "artist": "Donald Byrd", "label": "A New Perspective", "year": "1963" },
    { "category": "Bebop", "artist": "Jimmy Smith", "label": "Back at the Chicken Shack", "year": "1963" },
    { "category": "Bebop", "artist": "John Coltrane / Johnny Hartman", "label": "John Coltrane and Johnny Hartman", "year": "1963" },
    { "category": "Bebop", "artist": "Jackie McLean", "label": "One Step Beyond", "year": "1963" },
    { "category": "Bebop", "artist": "Joe Henderson", "label": "Page One", "year": "1963" },
    { "category": "Bebop", "artist": "Kenny Burrell", "label": "Midnight Blue", "year": "1963" },
    { "category": "Bebop", "artist": "Kenny Dorham", "label": "Una Mas", "year": "1963" },
    { "category": "Bebop", "artist": "Thelonious Monk", "label": "Big Band and Quartet in Concert [Live]", "year": "1963" },
    { "category": "Bebop", "artist": "The Thelonious Monk Quartet", "label": "Monk’s Dream", "year": "1963" },
    { "category": "Bebop", "artist": "Grant Green", "label": "Idle Moments", "year": "1964" },
    { "category": "Bebop", "artist": "Herbie Hancock", "label": "Empyrean Isles", "year": "1964" },
    { "category": "Bebop", "artist": "Lee Morgan", "label": "The Sidewinder", "year": "1964" },
    { "category": "Bebop", "artist": "Wayne Shorter", "label": "JuJu", "year": "1964" },
    { "category": "Bebop", "artist": "Herbie Hancock", "label": "Maiden Voyage", "year": "1965" },
    { "category": "Bebop", "artist": "Bobby Hutcherson", "label": "Dialogue", "year": "1965" },
    { "category": "Bebop", "artist": "Bobby Hutcherson", "label": "Components", "year": "1965" },
    { "category": "Bebop", "artist": "Horace Silver", "label": "Song for My Father", "year": "1965" },
    { "category": "Bebop", "artist": "Lee Morgan", "label": "Cornbread", "year": "1965" },
    { "category": "Bebop", "artist": "Wayne Shorter", "label": "Speak No Evil", "year": "1965" },
    { "category": "Bebop", "artist": "Wes Montgomery / Wynton Kelly Trio", "label": "Smokin’ at the Half Note [Live]", "year": "1965" },
    { "category": "Bebop", "artist": "Cannonball Adderley", "label": "Mercy, Mercy, Mercy! Live at ‘The Club’ [Live]", "year": "1966" },
    { "category": "Bebop", "artist": "Eddie Harris", "label": "The In Sound", "year": "1966" },
    { "category": "Bebop", "artist": "Jimmy Smith / Wes Montgomery", "label": "Jimmy & Wes: The Dynamic Duo", "year": "1966" },
    { "category": "Bebop", "artist": "Lee Morgan", "label": "Search for the New Land", "year": "1966" },
    { "category": "Bebop", "artist": "Wayne Shorter", "label": "Adam’s Apple", "year": "1966" },
    { "category": "Bebop", "artist": "Roland Kirk", "label": "The Inflated Tear", "year": "1968" },
    { "category": "Bebop", "artist": "Eddie Harris", "label": "The Electrifying Eddie Harris", "year": "1968" },
    { "category": "Bebop", "artist": "Les McCann / Eddie Harris", "label": "Swiss Movement [Live]", "year": "1969" },
    { "category": "Bebop", "artist": "Gary Burton", "label": "Alone at Last", "year": "1972" },
    { "category": "Bebop", "artist": "Jimmy Smith", "label": "Root Down [Live]", "year": "1972" },
    { "category": "Bebop", "artist": "Sonny Stitt", "label": "Tune-Up!", "year": "1972" },
    { "category": "Bebop", "artist": "Sonny Stitt", "label": "Constellation", "year": "1972" },
    { "category": "Bebop", "artist": "Joe Pass", "label": "Virtuoso", "year": "1973" },
    { "category": "Bebop", "artist": "Milt Jackson / Joe Pass / Ray Brown", "label": "The Big 3", "year": "1975" },
    { "category": "Bebop", "artist": "Rahsaan Roland Kirk", "label": "The Return of the 5000 Lb. Man", "year": "1976" },
    { "category": "Bebop", "artist": "Grant Green", "label": "Matador", "year": "1979" },
    { "category": "Bebop", "artist": "J.J. Johnson / Al Grey", "label": "Things Are Getting Better All the Time", "year": "1984" },
    { "category": "Bebop", "artist": "Wynton Marsalis", "label": "Black Codes From the Underground", "year": "1985" },
    { "category": "Bebop", "artist": "Jackie McLean", "label": "Dynasty", "year": "1990" },
    { "category": "Bebop", "artist": "Charlie Parker", "label": "Best of the Complete Savoy and Dial Studio Recordings [Compilation]", "year": "2002" }]
}

